[package]
name = "endhost-api-models"
version = "0.1.0"
edition.workspace = true

[dependencies]
# Local Dependencies
scion-proto = { workspace = true }

# Global Dependencies
async-trait = { workspace = true }
serde = { workspace = true }
url = { workspace = true }

[lints]
workspace = true
